name = "ChernoffFaces"
uuid = "e43c2c8f-3838-4c1d-b522-1af25db77ac2"
authors = ["irregular-rhomboid"]
version = "1.0.0-DEV"

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
ChernoffFacesMakieExt = "Makie"
ChernoffFacesPlotsExt = "Plots"

[compat]
GeometryBasics = "0.4"
Makie = "0.21"
Plots = "1.40"
RecipesBase = "1.3"
julia = "1.10"
