name = "ChernoffFaces"
uuid = "e43c2c8f-3838-4c1d-b522-1af25db77ac2"
authors = []
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[extensions]
ChernoffFacesMakieExt = "Makie"

[compat]
julia = "1.6.7"
